### ISSUE TITLE
Support for contacts.CreateOrUpdate

### ISSUE THREAD

**Issue by francas** [clarkmcc/go-hubspot#1]
Legacy API supports BatchCreateOrUpdate for contacts, it would be great to have support for this here too

https://legacydocs.hubspot.com/docs/methods/contacts/batch_create_or_update

**Comment by clarkmcc** [comment]
Does the legacy API have an OpenAPI spec by chance?

**Comment by francas** [comment]
Good question, I don't think they have it, you're probably aware of their endpoint listing OpenAPI supported APIs https://api.hubspot.com/api-catalog-public/v1/apis

**Comment by clarkmcc** [comment]
Gotcha, yes I am aware of that listing, in fact all the generated clients are created from whatever exists in that listing. 

https://github.com/clarkmcc/go-hubspot/blob/274fb76ee85ae6a4b44b4a5aa07eff8ac9a1ed5a/cmd/generate/main.go#L17

I specifically created this project to maintain and consolidate the generated clients. If you can track down an OpenAPI spec for the legacy API, I would be happy to add generation support for it, however if there is no way to generate a legacy client, I don't think a custom client would fit in the scope of this project.
