### ISSUE TITLE
Update to latest API spec

### ISSUE THREAD

**Issue by palsivertsen** [clarkmcc/go-hubspot#11]
Any chance of updating to the latest API specs?

**Comment by clarkmcc** [comment]
Hi! Sure thing, I'll re-run the code generation this week and get a new release out.

**Comment by palsivertsen** [comment]
@clarkmcc Thanks!

It seems GDPRApiService is missing from the [deals client](https://pkg.go.dev/github.com/clarkmcc/go-hubspot@v0.0.0-20240126004334-396353fd9cb8/generated/v3/deals#APIClient).

**Comment by erezrokah** [comment]
> It seems GDPRApiService is missing from the [deals client](https://pkg.go.dev/github.com/clarkmcc/go-hubspot@v0.0.0-20240126004334-396353fd9cb8/generated/v3/deals#APIClient).

Thanks for the update @clarkmcc, `GDPRApiService` is missing from:
```
github.com/clarkmcc/go-hubspot/generated/v3/quotes
github.com/clarkmcc/go-hubspot/generated/v3/products
github.com/clarkmcc/go-hubspot/generated/v3/companies
github.com/clarkmcc/go-hubspot/generated/v3/line_items
github.com/clarkmcc/go-hubspot/generated/v3/tickets
```

too I think

**Comment by clarkmcc** [comment]
Thanks! I'm slammed today and tomorrow but I'll get this resolved on Saturday. Also happy to accept a PR.

**Comment by clarkmcc** [comment]
Alright, sorry everyone that was a major oversight on my part. Can someone upgrade to @latest and try again?

**Comment by erezrokah** [comment]
Looks great on my end thanks for the quick response 🚀
