### ISSUE TITLE
Add a license to we can view it on godoc

### ISSUE THREAD

**Issue by abemedia** [clarkmcc/go-hubspot#2]
Right now it's not possible to view the docs: https://pkg.go.dev/github.com/clarkmcc/go-hubspot

Please add a license to enable this 🙂

**Comment by clarkmcc** [comment]
Thanks for the reminder! I'll get this taken care of as soon as I can.

**Comment by clarkmcc** [comment]
A license file has been added (https://github.com/clarkmcc/go-hubspot/commit/8c0e4f75dbeb3e9a84b11fb2d18ddc3e8b4c9e7e). I'm not sure how long it will take for godoc to recognize the update.
