### ISSUE TITLE
does auth with api key work?

### ISSUE THREAD

**Issue by dcu** [clarkmcc/go-hubspot#4]
I'm getting 403 when using api key authentication.

I'm using the owners api to list all owners. I activated the debug mode and I get:

```
"Authentication credentials not found. This API supports both API Key and OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview"
```

and I don't see my api key anywhere in the debug log

**Comment by dcu** [comment]
with `go generate` it includes the header but the generated code is broken. I fixed it manually and it works

**Comment by clarkmcc** [comment]
Hey @dcu, first of all, with the [upcoming deprecation](https://developers.hubspot.com/changelog/upcoming-api-key-sunset#:~:text=When%20is%20this%20change%20happening,API%20keys%20to%20be%20created.) for HubSpot API keys, I think I'll fix this by moving to private app API tokens. Will this work for you?

Also, I'll look into fixing the code generator. Thanks for reporting

**Comment by clarkmcc** [comment]
Give https://github.com/clarkmcc/go-hubspot/pull/5 a shot and let me know if you run into any additional issues.

**Comment by dcu** [comment]
this is failing:

```
./main.go:55:10: hubspotAPIKey.Apply(context.Background()) (no value) used as value
./main.go:55:30: cannot use context.Background() (value of type context.Context) as type hubspot.AuthorizationRequest in argument to hubspotAPIKey.Apply
./main.go:96:10: hubspotAPIKey.Apply(context.Background()) (no value) used as value
./main.go:96:30: cannot use context.Background() (value of type context.Context) as type hubspot.AuthorizationRequest in argument to hubspotAPIKey.Apply
```

I'm doing:
```
hubspot.NewAPIKeyAuthorizer("").Apply(context.Background())
```

how's the new way to do this?

EDIT: found the answer in the README

**Comment by dcu** [comment]
it works, thanks!

**Comment by dcu** [comment]
the access token for the private app works as well. thanks for the tip

**Comment by clarkmcc** [comment]
Yep, no problem. Sorry for changing the API out from under you. Once this package gets more utilized, I'm sure we'll settle into something stable.
